export function ruleSummary({ user, repos, score, langs, streak }) {
  const name = user.name || user.login;
  const best = [...repos].sort((a, b) => b.stargazers_count - a.stargazers_count)[0];
  const ranked = [...score.parts].sort((a, b) => b.pct - a.pct);
  const strong = ranked[0].key, weak = ranked[ranked.length - 1].key;
  const tips = {
    Repos: 'publish more finished projects', Stars: 'polish READMEs and share projects to attract stars',
    Followers: 'write about your work to grow an audience', Activity: 'commit more regularly',
    Languages: 'try a project in a new language', Tenure: 'keep building, since tenure grows with time',
  };
  return `${name} scores ${score.total}/100 (${score.grade}). ` +
    (langs[0] ? `Their work centres on ${langs[0].name}${langs[1] ? `, with ${langs[1].name} as a secondary language` : ''}. ` : '') +
    (best && best.stargazers_count > 0 ? `Their most popular repository is ${best.name} with ${best.stargazers_count} stars. ` : '') +
    `Strongest area: ${strong.toLowerCase()}. Biggest opportunity: ${weak.toLowerCase()}, so ${tips[weak]}.` +
    (streak.longest ? ` Longest contribution streak this year: ${streak.longest} days.` : '');
}

export async function aiSummary(data) {
  const local = { text: ruleSummary(data), source: 'Smart insights (generated in your browser)' };
  const token = import.meta.env.VITE_HF_TOKEN;
  if (!token) return local;
  const { user, repos, score, langs, streak } = data;
  const facts = JSON.stringify({
    name: user.name || user.login, bio: user.bio, score: score.total, grade: score.grade, stars: score.stars,
    followers: user.followers, repos: repos.length, contributionsLastYear: score.yearly, longestStreak: streak.longest,
    languages: langs.slice(0, 5).map((l) => l.name),
    topRepos: repos.slice(0, 5).map((r) => ({ name: r.name, stars: r.stargazers_count, description: r.description })),
  });
  try {
    const res = await fetch('https://router.huggingface.co/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body: JSON.stringify({
        model: 'meta-llama/Llama-3.1-8B-Instruct', max_tokens: 250,
        messages: [{ role: 'user', content: `You are a friendly senior engineer reviewing a GitHub profile. In 4 short sentences: strengths, gaps, and one project to build next. Use only these facts: ${facts}` }],
      }),
    });
    const text = (await res.json()).choices?.[0]?.message?.content?.trim();
    return text ? { text, source: 'Generated by Llama 3.1 via Hugging Face' } : local;
  } catch { return local; }
}
